services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=cryptography
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=admin
    ports:
      - '3306:3306'
    expose:
      - '3306'